// ── Memory Types ──
export type { MemoryEntry, MemoryStore, MemorySnapshot, MemoryEmotionTag, PlanConversationData, VoiceBookmark, InteractionRecord, SummaryEntry, VectorEntry, PreferenceSummary, ConsecutiveDayTopic, TopicToolMapping } from './types'
export type { MemoryRetrievalResult, MemoryUpdateInput, IMemoryPlugin } from './IMemoryPlugin'

// ── Memory Services ──
export { MemoryService } from './MemoryService'
export { sessionMemory } from './SessionMemory'
export { EngineeringMemory } from './EngineeringMemory'
export { DecisionStore } from './DecisionStore'
export { SummaryMemory } from './SummaryMemory'
export { MetaController } from './MetaController'
export { MemoryContextProvider, type InjectionContext } from './MemoryContextProvider'
export { PlanMemoryRecall, planMemoryRecall as defaultPlanMemoryRecall } from './PlanMemoryRecall'
export { TaskStepRecorder } from './TaskStepRecorder'
export { UnifiedMemoryQuery } from './UnifiedMemoryQuery'
export { VectorMemory } from './VectorMemory'
export { MemoryCleaner } from './MemoryCleaner'
export { MemoryCompressor } from './MemoryCompressor'
export { MemoryIndexer } from './MemoryIndexer'
export { MemorySleepManager } from './MemorySleepManager'
export { MemorySnapshotManager } from './MemorySnapshotManager'
export { MemoryUtilityTracker } from './MemoryUtilityTracker'
export { KeywordFrequencyTracker } from './KeywordFrequencyTracker'
export { InteractionTracker } from './InteractionTracker'
export { classifyVoiceMemoryIntent, formatMemoryFeedback } from './VoiceMemoryClassifier'
export { runVoiceMemoryShortcut } from './VoiceMemoryShortcut'
export { VoiceBookmarkService } from './VoiceBookmarkService'
export { KnowledgeBaseService } from './KnowledgeBaseService'
export { KnowledgeGraph } from './KnowledgeGraph'
export { FictionalMemoryGenerator } from './FictionalMemoryGenerator'
export { BehaviorWeightingService } from './BehaviorWeightingService'
export { AdaptiveOrchestrator } from './AdaptiveOrchestrator'
export { MemoryEvolutionBridge } from './MemoryEvolutionBridge'
export { ExperienceMemoryService } from './plan-memory-blog/ExperienceMemoryService'
export { BlogMemoryAssistant } from './plan-memory-blog/BlogMemoryAssistant'
export { BlogMemoryRecorder } from './plan-memory-blog/BlogMemoryRecorder'
export { BlogMemoryRetriever } from './plan-memory-blog/BlogMemoryRetriever'

// ── Memory Utilities ──
export { EMBED_DIM, cosineSimilarity, fallbackEmbed, getEmbedding } from './embedding'

// ── Sidecar ──
export { MemorySidecar } from './sidecar/MemorySidecar'
export type { ISidecarPlugin, AddEntryContext, AddEntryResult, GetEntriesResult, GetFormattedContextResult } from './sidecar/types'