// ── Memory Types ──
export type { MemoryEntry, MemoryStore, MemorySnapshot, MemoryEmotionTag, PlanConversationData, VoiceBookmark, InteractionRecord, SummaryEntry, VectorEntry, PreferenceSummary, ConsecutiveDayTopic, TopicToolMapping } from '@akemi-mio/intelligence-memory'
export type { MemoryRetrievalResult, MemoryUpdateInput, IMemoryPlugin } from '@akemi-mio/intelligence-memory'

// ── Memory Services ──
export { MemoryService } from '@akemi-mio/intelligence-memory'
export { sessionMemory as defaultSessionMemory } from '@akemi-mio/intelligence-memory'
export { EngineeringMemory } from '@akemi-mio/intelligence-memory'
export { DecisionStore } from '@akemi-mio/intelligence-memory'
export { SummaryMemory } from '@akemi-mio/intelligence-memory'
export { MetaController } from '@akemi-mio/intelligence-memory'
export { MemoryContextProvider, type InjectionContext } from '@akemi-mio/intelligence-memory'
export { PlanMemoryRecall, defaultPlanMemoryRecall } from '@akemi-mio/intelligence-memory'
export { TaskStepRecorder } from '@akemi-mio/intelligence-memory'
export { UnifiedMemoryQuery } from '@akemi-mio/intelligence-memory'
export { VectorMemory } from '@akemi-mio/intelligence-memory'
export { MemoryCleaner } from '@akemi-mio/intelligence-memory'
export { MemoryCompressor } from '@akemi-mio/intelligence-memory'
export { MemoryIndexer } from '@akemi-mio/intelligence-memory'
export { MemorySleepManager } from '@akemi-mio/intelligence-memory'
export { MemorySnapshotManager } from '@akemi-mio/intelligence-memory'
export { MemoryUtilityTracker } from '@akemi-mio/intelligence-memory'
export { KeywordFrequencyTracker } from '@akemi-mio/intelligence-memory'
export { InteractionTracker } from '@akemi-mio/intelligence-memory'
export { classifyVoiceMemoryIntent, formatMemoryFeedback } from '@akemi-mio/intelligence-memory'
export { runVoiceMemoryShortcut } from '@akemi-mio/intelligence-memory'
export { VoiceBookmarkService } from '@akemi-mio/intelligence-memory'
export { KnowledgeBaseService } from '@akemi-mio/intelligence-memory'
export { KnowledgeGraph } from '@akemi-mio/intelligence-memory'
export { FictionalMemoryGenerator } from '@akemi-mio/intelligence-memory'
export { BehaviorWeightingService } from '@akemi-mio/intelligence-memory'
export { AdaptiveOrchestrator } from '@akemi-mio/intelligence-memory'
export { MemoryEvolutionBridge } from '@akemi-mio/intelligence-memory'
export { ExperienceMemoryService } from '@akemi-mio/intelligence-memory'
export { BlogMemoryAssistant } from '@akemi-mio/intelligence-memory'
export { BlogMemoryRecorder } from '@akemi-mio/intelligence-memory'
export { BlogMemoryRetriever } from '@akemi-mio/intelligence-memory'

// ── Memory Utilities ──
export { EMBED_DIM, cosineSimilarity, fallbackEmbed, getEmbedding } from '@akemi-mio/intelligence-memory'

// ── Sidecar ──
export { MemorySidecar } from '@akemi-mio/intelligence-memory'
export type { ISidecarPlugin, AddEntryContext, AddEntryResult, GetEntriesResult, GetFormattedContextResult } from '@akemi-mio/intelligence-memory'